### ISSUE TITLE
maven.wagyourtail.xyz connection issues

### ISSUE THREAD

**Issue by 3arthqu4ke** [unimined/unimined#114]
I am currently running into connection issues to your maven @wagyourtail , both on github actions and on my machine, could you look into your server? Also your website is down.

E.g. downloading https://maven.wagyourtail.xyz/releases/xyz/wagyourtail/unimined/unimined/1.1.1/unimined-1.1.1.jar fails.
```
Caused by: org.gradle.api.resources.ResourceException: Could not get resource 'https://maven.wagyourtail.xyz/releases/xyz/wagyourtail/unimined/unimined/1.1.1/unimined-1.1.1.jar'.
	at org.gradle.internal.resource.ResourceExceptions.failure(ResourceExceptions.java:74)
	...
Caused by: org.apache.http.ConnectionClosedException: Premature end of Content-Length delimited message body (expected: 9,085,394; received: 1,556,110)
	at org.apache.http.impl.io.ContentLengthInputStream.read(ContentLengthInputStream.java:178)
	...
```

**Comment by wagyourtail** [comment]
Looks like the server ran out of disk space. Fixed now.
