### ISSUE TITLE
Using side CLIENT with Forge causes patches to fail due to checksum mismatch

### ISSUE THREAD

**Issue by ZeroMemes** [unimined/unimined#36]
I LOVE Forge!!!!!

```
[Unimined/Forge] transforming minecraft jar for FG3
minecraft: MinecraftJar(path=.gradle\unimined\net\minecraft\minecraft\1.19.4\minecraft-1.19.4-client.jar)
Running binpatcher with args: --clean .gradle\unimined\net\minecraft\minecraft\1.19.4\minecraft-1.19.4-client.jar --output .gradle\unimined\net\minecraft\minecraft\1.19.4\1.19.4-45.1.0\forge-client-1.19.4-official.jar --apply .gradle\unimined\net\minecraft\minecraft\1.19.4\1.19.4-45.1.0\binpatches.lzma --data --unpatched
Applying:
  Clean:     .gradle\unimined\net\minecraft\minecraft\1.19.4\minecraft-1.19.4-client.jar
  Output:    .gradle\unimined\net\minecraft\minecraft\1.19.4\1.19.4-45.1.0\forge-client-1.19.4-official.jar
  KeepData:  true
  Unpatched: true
  Pack200:   false
  Legacy:    false
Loading patches file: .gradle\unimined\net\minecraft\minecraft\1.19.4\1.19.4-45.1.0\binpatches.lzma

...

  Patching net/minecraft/client/main/Main$1 1/1
java.io.IOException: Patch expected net/minecraft/client/main/Main$1 to have the checksum 4f63f67d but it was 2c2cbc92
        at net.minecraftforge.binarypatcher.Patcher.patch(Patcher.java:197)
        at net.minecraftforge.binarypatcher.Patcher.process(Patcher.java:149)
        at net.minecraftforge.binarypatcher.ConsoleTool.main(ConsoleTool.java:161)
        at xyz.wagyourtail.unimined.internal.minecraft.patch.forge.fg3.FG3MinecraftTransformer.transform(FG3MinecraftTransformer.kt:292)
        at xyz.wagyourtail.unimined.internal.minecraft.patch.forge.ForgeMinecraftTransformer.transform(ForgeMinecraftTransformer.kt:363)
        at xyz.wagyourtail.unimined.internal.minecraft.MinecraftProvider$minecraftFiles$1.invoke(MinecraftProvider.kt:109)
        at xyz.wagyourtail.unimined.internal.minecraft.MinecraftProvider$minecraftFiles$1.invoke(MinecraftProvider.kt:99)
        at xyz.wagyourtail.unimined.util.DefaultMap.get(DefaultMap.kt:11)
        at xyz.wagyourtail.unimined.internal.minecraft.MinecraftProvider.getMinecraft(MinecraftProvider.kt:116)
        at xyz.wagyourtail.unimined.internal.minecraft.MinecraftProvider$minecraftFileDev$2.invoke(MinecraftProvider.kt:359)
        at xyz.wagyourtail.unimined.internal.minecraft.MinecraftProvider$minecraftFileDev$2.invoke(MinecraftProvider.kt:357)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at xyz.wagyourtail.unimined.internal.minecraft.MinecraftProvider.getMinecraftFileDev(MinecraftProvider.kt:357)
        at xyz.wagyourtail.unimined.internal.minecraft.patch.forge.fg3.FG3MinecraftTransformer.createLegacyClasspath(FG3MinecraftTransformer.kt:367)
        at xyz.wagyourtail.unimined.internal.minecraft.patch.forge.fg3.FG3MinecraftTransformer.applyClientRunTransform(FG3MinecraftTransformer.kt:375)
        at xyz.wagyourtail.unimined.internal.minecraft.patch.forge.ForgeMinecraftTransformer.applyClientRunTransform(ForgeMinecraftTransformer.kt:455)
        at xyz.wagyourtail.unimined.internal.minecraft.MinecraftProvider$clientRun$1.invoke(MinecraftProvider.kt:218)
        at xyz.wagyourtail.unimined.internal.minecraft.MinecraftProvider$clientRun$1.invoke(MinecraftProvider.kt:218)
        at xyz.wagyourtail.unimined.internal.runs.RunsProvider$configFirst$1$1.invoke(RunsProvider.kt:40)
        at xyz.wagyourtail.unimined.internal.runs.RunsProvider$configFirst$1$1.invoke(RunsProvider.kt:39)
        at xyz.wagyourtail.unimined.internal.runs.RunsProvider$transformedRunConfig$1.invoke(RunsProvider.kt:18)
        at xyz.wagyourtail.unimined.internal.runs.RunsProvider$transformedRunConfig$1.invoke(RunsProvider.kt:16)
        at xyz.wagyourtail.unimined.util.DefaultMap.get(DefaultMap.kt:11)
        at xyz.wagyourtail.unimined.internal.runs.RunsProvider.createGradleRuns(RunsProvider.kt:75)
        at xyz.wagyourtail.unimined.internal.runs.RunsProvider.access$createGradleRuns(RunsProvider.kt:10)
        at xyz.wagyourtail.unimined.internal.runs.RunsProvider$apply$1.invoke(RunsProvider.kt:55)
        at xyz.wagyourtail.unimined.internal.runs.RunsProvider$apply$1.invoke(RunsProvider.kt:49)
        at xyz.wagyourtail.unimined.internal.runs.RunsProvider.apply$lambda$2(RunsProvider.kt:49)
```

**Comment by wagyourtail** [comment]
oh. that's odd... it's trying to patch without remapping to srg first

**Comment by wagyourtail** [comment]
fixed with https://github.com/unimined/unimined/commit/55cd70113cf872b1f4cd1fe8a34aaa473afe27ad
