### ISSUE TITLE
Trying to run 1.2.5 forge client always fails due to wrong method signature.

### ISSUE THREAD

**Issue by MartinSVK12** [unimined/unimined#38]
```
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
	at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)
Caused by: java.lang.NoSuchMethodError: net.lenni0451.classtransform.TransformerManager.addTransformer(Lxyz/wagyourtail/unimined/jarmodagent/shadow/org/objectweb/asm/tree/ClassNode;Z)Ljava/util/Set;
	at xyz.wagyourtail.unimined.jarmodagent.transformer.TransformerListBuilder.build(TransformerListBuilder.java:39)
	at xyz.wagyourtail.unimined.jarmodagent.transformer.JarModder.registerTransforms(JarModder.java:71)
	at xyz.wagyourtail.unimined.jarmodagent.JarModAgent.premain(JarModAgent.java:42)
	... 6 more
Exception in thread "main" FATAL ERROR in native method: processing of -javaagent failed
```
seems like [this commit](https://github.com/unimined/JarModAgent/commit/e2ac53f7a3eac9a63fb19eade3bdaf6530c000fa) broke it?

**Comment by thecatcore** [comment]
Is it still happening? the relocation was removed.

**Comment by wagyourtail** [comment]
fixed with https://github.com/unimined/unimined/commit/35637a989b425d641ac0358cd31ed5f699be630f
