### ISSUE TITLE
Failing to remap a comment in access transformer file

### ISSUE THREAD

**Issue by airplane** [unimined/unimined#45]
Trying to use legacy fabric mappings on a forge/legacy fabric project.
Seems to be trying to read the first comment in forge's [forge_at.cfg](https://github.com/MinecraftForge/MinecraftForge/blob/d06e0ad71b8471923cc809dde58251de8299a143/src/main/resources/forge_at.cfg#L1)

[Log](https://pastebin.com/PsCE0Bx7)

<details><summary>Mappings Setup</summary>

```groovy
unimined.minecraft {
	version project.minecraft_version

	mappings {
		legacyIntermediary(1)
		legacyYarn(514)
	}

	legacyFabric {
		loader project.fabric_version
	}

	minecraftForge {
		loader project.forge_version
		mixinConfig "notwitchkeybind.mixins.json"
	}
}
```

</details>

**Comment by wagyourtail** [comment]
you're mis-attributing the issue. the real cause is the 
```
Caused by: java.lang.RuntimeException: Unfixable conflicts
	at net.fabricmc.tinyremapper.TinyRemapper.handleConflicts(TinyRemapper.java:867)
	at net.fabricmc.tinyremapper.TinyRemapper.propagate(TinyRemapper.java:767)
	at net.fabricmc.tinyremapper.TinyRemapper.mrjRefresh(TinyRemapper.java:1046)
	at net.fabricmc.tinyremapper.TinyRemapper.getEnvironment(TinyRemapper.java:1152)
```
	
add
```
    minecraftRemapper.config {
        ignoreConflicts(true)
    }
```
to the minecraft block
