### ISSUE TITLE
Support for projects that use `mojmap()` but that rely on mods that use conflicting method names

### ISSUE THREAD

**Issue by tolland** [unimined/unimined#74]
This is likely a support or documentation request, but I was hoping I could get some pointers on how to proceed.

I am currently looking at an issue with baritones' support for building litematica schematics with multiple subregions, hence I am working from a baritone [branch](https://github.com/cabaletta/baritone/compare/1.20.4...tolland:baritone:1.20.4-bump1) into which I have bumped some versions and I have dropped [litematica](https://mediafilez.forgecdn.net/files/5096/807/malilib-fabric-1.20.4-0.18.1.jar) and [malilib](https://mediafilez.forgecdn.net/files/5170/70/litematica-fabric-1.20.4-0.17.2.jar) jars in the `fabric/run/client/mods` directory.

With this branch I can build baritone jar and use that jar in a fabric minecraft (with litematica/malilib). however if I try to run the branch from intelllij, or use the gradle `:fabric:runClient` task the client crashes with a stackoverflow relating to a conflicting method name between mojmap and malilib. This obviously makes further development on that a big PITA ;-)

The error manifests like so:
```
Caused by: java.lang.StackOverflowError
        at com.mojang.blaze3d.platform.InputConstants.isKeyDown(InputConstants.java:473) ~[minecraft-1.20.4-fabric-merged+fixed-mojmap+intermediary.jar:?]
        at net.minecraft.client.gui.screens.Screen.hasShiftDown(Screen.java:377) ~[minecraft-1.20.4-fabric-merged+fixed-mojmap+intermediary.jar:?]
        at fi.dy.masa.malilib.gui.GuiBase.isShiftDown(GuiBase.java:675) ~[malilib-0.18.0-64b5720b4b825f21.jar:?]
        at fi.dy.masa.malilib.gui.GuiTextFieldGeneric.setCursorPosition(GuiTextFieldGeneric.java:93) ~[malilib-0.18.0-64b5720b4b825f21.jar:?]
        at net.minecraft.client.gui.components.EditBox.moveCursorTo(EditBox.java:256) ~[minecraft-1.20.4-fabric-merged+fixed-mojmap+intermediary.jar:?]
```

The suggestion from the malilib discord is that I should remap the methods from baritone, which is using unimined gradle plugin. However for the life of me, I can't work out how to do that from the various issues I have looked at, or the documentation.

I guess that I am looking to implement this:
![2024-05-29_16-55](https://github.com/unimined/unimined/assets/91288/ef75b304-dfe5-4323-9623-8315d588b669)

Related issues:
* https://github.com/cabaletta/baritone/issues/4375
* https://github.com/cabaletta/baritone/issues/4325
* https://github.com/maruohon/malilib/issues/149

**Comment by wagyourtail** [comment]
what you want is stubs
example: <https://github.com/JsMacros/JsMacros/blob/8176becfb614b0817d4f5d9bcd02d66c1a192b82/build.gradle#L89>

**Comment by wagyourtail** [comment]
https://github.com/unimined/unimined/blob/main/docs/MAPPINGS.md#overriding-mappings
