### ISSUE TITLE
Can't use AT2AW convertors because Unimined is excluding required dependency of AccessTransformer

### ISSUE THREAD

**Issue by thecatcore** [unimined/unimined#75]
```
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.NoClassDefFoundError: org/apache/logging/log4j/LogManager [in thread "Daemon worker Thread 16"]
	at net.neoforged.accesstransformer.parser.AccessTransformerList.<clinit>(AccessTransformerList.java:18)
	at xyz.wagyourtail.unimined.internal.mapping.at.AccessTransformerApplier.at2aw(AccessTransformerApplier.kt:356)
	at xyz.wagyourtail.unimined.internal.minecraft.patch.access.AccessConvertImpl.at2aw(AccessConvertImpl.kt:55)
	at xyz.wagyourtail.unimined.internal.minecraft.patch.access.AccessConvertImpl.at2aw(AccessConvertImpl.kt:53)
	at xyz.wagyourtail.unimined.internal.minecraft.patch.access.transformer.AccessTransformerMinecraftTransformer.at2aw(AccessTransformerMinecraftTransformer.kt)
```

Neoforge's AccessTransformer depends on Log4j, however it's [excluded by Unimined](https://github.com/unimined/unimined/blob/main/build.gradle.kts#L176) and never included back in the released pom?

Tested using Unimined 1.2.6

**Comment by wagyourtail** [comment]
strange. gradle's supposed to include log4j...
